# General application settings
app:
  name: SortBook v5
  text_preview_chars: 10000
  request_timeout: 180

commands:
  run:
    dry_run: true
    test_file:
    limit: 0
    offset: 0
    use_redis: false
    verbose: false
    reset: true
    n8n_test: false

paths:
  book_sources: "/home/antares/project/livres"
  book_target: "/home/antares/project/livres_sorted"

database:
  dsn: "postgresql://user:password@localhost:5432/sortbook_db"

redis:
  host: "localhost"
  port: 6379
  db: 0

services:
  n8n:
    prod_url: "https://n8n.antares.local/webhook/"
    test_url: "https://n8n.antares.local/webhook-test/"
    workflow_path: "sortebook_v5"
    verify_ssl: false

ocr:
  languages:
    - fr
    - en
  use_gpu: true
  max_chars: 3000
  detail: 0
  paragraph: false
  contrast_ths: 0.05
  adjust_contrast: 0.6
  text_threshold: 0.35
  low_text: 0.3
  link_threshold: 0.6
